duffelhq/duffel-components

- .github/workflows/autoapprove.yml
- .github/workflows/release.yml
- .husky/post-commit
- commitlint.config.js
- package.json
- yarn.lock
__What__
This implements the script that automatically tag PRs for release. Once a PR is merged into the main branch, the script will take care of uploading assets to our CDN and publishing the package to npm. The first release will be version 3.0.0 (we archived components-javascript on version 2.7.20. 
In addition to it, separately, there's a script that will check if the commit has been tagged for release, and if so, it'll publish the package to npm and upload the assets to our CDN.
> Drafts the script to publish to npm and run cdn upload

- .storybook/__snapshots__/Storyshots.test.js.snap
- src/components/Modal.tsx
- src/styles/components/Modal.css
__what__
Before:
https://github.com/duffelhq/duffel-components/assets/2934495/b19021da-96af-4fd1-bee5-5122e0a32af5
After:
https://github.com/duffelhq/duffel-components/assets/2934495/da9ccbe3-8e2e-4e06-ac05-e318bcac6fb7
> Removes flash when component loads

- .github/renovate.json
> Update renovate to run monthly

- package.json
- yarn.lock
https://github.com/duffelhq/duffel-components/security/dependabot/4
> build: fix word-wrap vulnerability

- src/components/DuffelAncillaries/DuffelAncillaries.tsx
- src/components/DuffelAncillaries/seats/SeatMap.tsx
- src/lib/getPassengerName.ts
Attempt to address the following Sentries:
- https://duffel.sentry.io/issues/4236512823/?project=4504854496149504&query=is%3Aunresolved&referrer=issue-stream&sort=priority&statsPeriod=14d&stream_index=5
- https://duffel.sentry.io/issues/4299534659/?project=4504854496149504&query=is%3Aunresolved&referrer=issue-stream&sort=priority&statsPeriod=14d&stream_index=2
- https://duffel.sentry.io/issues/4079438925/?project=4504854496149504&query=is%3Aunresolved&referrer=issue-stream&sort=priority&statsPeriod=14d&stream_index=7
- https://duffel.sentry.io/issues/4249504137/?project=4504854496149504&query=is%3Aunresolved&referrer=issue-stream&sort=priority&statsPeriod=14d&stream_index=2
> fix: attempt to fix a few type errors

- src/lib/getBaggageServiceDescription.ts
- src/lib/retrieveOffer.ts
This PR removes a couple Sentry calls that I don’t think are adding much value, but please let me know if you disagree - maybe I just don’t have enough context.
> fix: remove a couple sentry calls 

- package.json
I've published 3.0.1  according to instructions in https://github.com/duffelhq/duffel-components/blob/main/CONTRIBUTING.md.
> build: up version to 3.0.1

- package.json
> build: up version to 3.1.0

- .storybook/__snapshots__/Storyshots.test.js.snap
- package.json
- src/components/DuffelAncillaries/DuffelAncillaries.tsx
- src/components/DuffelAncillaries/bags/BaggageSelectionModalBodyPassenger.tsx
- src/components/DuffelAncillaries/bags/BaggageSelectionModalHeader.tsx
- src/components/DuffelAncillaries/cancel_for_any_reason/CfarSelectionModalFooter.tsx
- src/components/DuffelAncillaries/seats/SeatSelectionModalHeader.tsx
- src/components/DuffelPayments/DuffelPayments.tsx
- src/fixtures/offers/off_1.json
- src/stories/Button.stories.tsx
- src/stories/DuffelAncillaries.stories.tsx
- src/styles/components/Card.css
- src/styles/components/CfarSelectionModal.css
- src/styles/components/Legend.css
- src/styles/components/LoadingState.css
- src/styles/components/PassengerSelect.css
- src/styles/components/Seat.css
- src/styles/components/Tabs.css
Also fixes the strange "0" appearing in the baggage modal when no baggage was included:
> Fix colours for other elements when accent is white

- .husky/post-commit
- .husky/pre-commit
- package.json
- yarn.lock
Follow up to stay consistent with hq, dashboard and design system
> Removes husky

- package.json
- yarn.lock
To resolve https://github.com/duffelhq/duffel-components/security/dependabot/6
> Adds resolution for safe version of @babel/traverse

- src/lib/convertDurationToString.ts
- src/lib/getDurationString.ts
- src/lib/isISO8601Duration.ts
__What__
We'll need some helpers for the slice component, this adds that
> Adds new helpers

- src/lib/getDateObject.ts
- src/lib/getDateString.ts
- src/lib/getDayDiff.ts
- src/lib/getTimeString.ts
- src/lib/isValidDateString.ts
- src/lib/toUTCDate.ts
- src/tests/lib/getDateObject.test.ts
- src/tests/lib/getDateString.spec.ts
- src/tests/lib/getDayDiff.test.ts
- src/tests/lib/getTimeString.test.ts
- src/tests/lib/isValidDateString.test.ts
- src/tests/lib/toUTCDate.test.ts
__What__
Adds some date helpers we'll need for the itinerary card component
> More date helpers

- src/lib/getAirlinesText.ts
- src/lib/getCarriers.ts
- src/lib/getDateObject.ts
- src/lib/getDateString.ts
- src/lib/getDayDiff.ts
- src/lib/getTimeString.ts
- src/lib/isValidDateString.ts
- src/lib/toUTCDate.ts
- src/tests/lib/getAirlinesText.test.ts
- src/tests/lib/getCarriers.test.ts
- src/tests/lib/getDateObject.test.ts
- src/tests/lib/getDateString.spec.ts
- src/tests/lib/getDayDiff.test.ts
- src/tests/lib/getTimeString.test.ts
- src/tests/lib/isValidDateString.test.ts
- src/tests/lib/toUTCDate.test.ts
__what__
Adds missing helpers that handle getting information from the offer slice object. This will be needed for our itinerary card.
> Flights helpers

- src/components/AirlineLogo/AirlineLogo.tsx
- src/lib/getAirlinesText.ts
- src/lib/getCarriers.ts
- src/lib/getDateObject.ts
- src/lib/getDateString.ts
- src/lib/getDayDiff.ts
- src/lib/getTimeString.ts
- src/lib/isValidDateString.ts
- src/lib/toUTCDate.ts
- src/stories/AirlineLogo.stories.tsx
- src/tests/lib/getAirlinesText.test.ts
- src/tests/lib/getCarriers.test.ts
- src/tests/lib/getDateObject.test.ts
- src/tests/lib/getDateString.spec.ts
- src/tests/lib/getDayDiff.test.ts
- src/tests/lib/getTimeString.test.ts
- src/tests/lib/isValidDateString.test.ts
- src/tests/lib/toUTCDate.test.ts
__what__
This add the airline logo component for internal use:
> Airline logo

- package.json
- src/components/DuffelAncillaries/cancel_for_any_reason/CfarSelectionModal.tsx
- src/types/DuffelAncillariesProps.ts
- yarn.lock
__What__
A follow up to support this type change: https://github.com/duffelhq/duffel-api-javascript/pull/859
> Fixes metadata

- package.json
- src/components/DuffelAncillaries/bags/BaggageSelectionModalHeader.tsx
- src/components/DuffelAncillaries/seats/SeatElement.tsx
- src/components/DuffelAncillaries/seats/SeatSelectionModalHeader.tsx
- src/components/PlacesLookup/PlacesLookup.tsx
__what__
Adds `type=button` to all button elements so if the components are used inside forms it won't trigger a form submission.
> Adds type=button

- package.json
- src/components/DuffelCardForm/DuffelCardForm.tsx
- src/components/DuffelCardForm/lib/getIFrameEventListener.ts
- src/components/DuffelCardForm/lib/getTokenFromClientKey.ts
- src/components/DuffelCardForm/lib/types.ts
- src/stories/DuffelCardForm.stories.tsx
__what__
This PR adds the interface to allow integrators to customise the styles for the duffel card component. 
This PR is counterpart to https://github.com/duffelhq/token-proxy/pull/260.
> Enable custom styles

- package.json
- src/components/DuffelCardForm/DuffelCardForm.tsx
- src/components/DuffelCardForm/lib/types.ts
- src/stories/DuffelCardForm.stories.tsx
- yarn.lock
__What__
so we can test things on staging. [See slack thread](https://duffel.slack.com/archives/CUC7FC8CA/p1704980737367629)
> Allows for staging as well when using DuffelCard form

- package.json
- src/components/DuffelAncillaries/bags/BaggageSelectionModalBodyPassenger.tsx
- src/types/DuffelAncillariesProps.ts
Reverts duffelhq/duffel-components#203
> Revert "Fix baggage selection restriction bug"

- src/components/shared/SliceCarriersTitle.tsx
- src/stories/SliceCarriersTitle.stories.tsx
- src/styles/components/SliceCarriersTitle.css
- src/styles/global.css
__what__
Crates a component to display the operating and marketing carriers of a slice:
> Creates SliceCarriersTitle component

- src/components/DuffelCardForm/lib/getPathnameForIntent.ts
__what__
To make it easier to work with k8 ingress rules. [Read more about it on slack](https://duffel.slack.com/archives/CUC7FC8CA/p1706619666754739?thread_ts=1706265078.842159&cid=CUC7FC8CA)
> Updates pathname prefix

- src/components/DuffelNGSView/SliceSummary.tsx
- src/styles/components/SliceSummary.css
__what__
Updates slice summary to include missing lines:
| Before | After |
|---|---|
| ![screenshot_2024-01-31_at_11 33 38_720](https://github.com/duffelhq/duffel-components/assets/2934495/df48ecf6-94f0-42f5-b88e-8d29d306c841) | <img width="800" alt="Screenshot 2024-01-31 at 13 44 51" src="https://github.com/duffelhq/duffel-components/assets/2934495/5bd1fa55-ed2f-4cb7-9131-f5af022dbd9e"> |
> Adds missing lines to slices with stops

- package.json
- src/index.ts
This will expose the DuffelNGSView component so we can use and demo it in the dashboard.
> Release NGS so we can use it in dashboard

- package.json
Update version to 3.6.2 to get latest NGS changes
> Bump to 3.6.2

- examples/card-form-examples/tsconfig.json
- examples/just-typescript/tsconfig.json
- examples/next/tsconfig.json
- package.json
- src/styles/components/DuffelNGSView.css
- tsconfig.json
The shelf cards are slightly cut off in the dashboard:
Companion PR: https://github.com/duffelhq/dashboard/pull/4842
> Fix space for shelf cards

- package.json
- src/components/DuffelNGSView/NGSSliceFareCard.tsx
- src/components/DuffelNGSView/NGSTable.tsx
- src/stories/NGSSliceFareCard.stories.tsx
- src/styles/components/NGSSliceFareCard.css
- src/styles/components/NGSTable.css
- yarn.lock
This fixes some issues with the table display when there were many offers in a drawer (which wasn't really accounted for before). I also removed a couple props that were previously used to compare shelves but don't apply anymore.
Includes version bump so I can release.
Example scroll (fake data):
https://github.com/duffelhq/duffel-components/assets/1416759/75e76e6c-3e30-42d4-84ff-ea4ed2fe3dfb
> Fix NGS scroll

- package.json
- src/components/MapboxPlacesLookup/MapboxPlacesLookup.tsx
- src/components/MapboxPlacesLookup/lib/getPlacesFromMapboxClient.ts
- src/components/Stays/StaysRoomRateCard.tsx
- src/stories/DuffelCardForm.stories.tsx
- src/stories/MapboxPlacesLookup.stories.tsx
- src/styles/components/PlacesLookup.css
__what__
Improves mapbox place lookup UX based on [report from slack](https://duffel.slack.com/archives/C04BCM0H42W/p1711030068195929?thread_ts=1711022887.557549&cid=C04BCM0H42W). These changes are required for https://github.com/duffelhq/platform/pull/18081
https://github.com/duffelhq/duffel-components/assets/2934495/1ad158b7-be41-4ba2-8003-d5b7e0b636d2
> [UXP-3410] Improves mapbox place 

- package.json
- src/components/DuffelNGSView/AirlineSelector.tsx
- src/components/DuffelNGSView/FilterControl.tsx
- src/stories/DuffelNGSView.stories.tsx
- src/styles/components/FilterControl.css
__what__
Sets airline popover to max height and enables scrolling within it:
https://github.com/duffelhq/duffel-components/assets/2934495/472abf09-b494-443a-8e0f-f48709ed3cbe
> Overflow y on airline popover

- package.json
- src/components/DuffelNGSView/DuffelNGSView.tsx
- src/components/DuffelNGSView/SortingControl.tsx
- src/components/DuffelNGSView/lib/sort-ngs-rows-by-recommended.ts
Add "Recommended" sort which works as a product of duration and price as described in this Slack thread: https://duffel.slack.com/archives/C06A8HUCDPW/p1715334751431589
Looks roughly right from this example:
> Add recommended sort

- .github/CODEOWNERS
Context here: https://duffel.slack.com/archives/CEA36CWLX/p1719225090881319
> Remove UXP as codeowners

- package.json
- src/functions/createThreeDSecureSession/client.ts
- src/functions/createThreeDSecureSession/createThreeDSecureSession.ts
- src/tests/functions/createThreeDSecureSession.test.ts
Based on: https://github.com/duffelhq/platform/pull/20405/files
> Rename fields to match API

- src/functions/createThreeDSecureSession/client.ts
__What__ 
Makes updates to support the changes on our payments API.
> API related changes

- package.json
- src/components/Stays/StaysSummary.tsx
This shows the postal code where available in the address for the stay
Storybook sample below:
> Show stay's postal code in stays summary

- src/components/DuffelCardForm/lib/types.ts
- src/functions/createThreeDSecureSession/client.ts
- src/functions/createThreeDSecureSession/createThreeDSecureSession.ts
To include better comments describing properties
> Improves types

- src/functions/createThreeDSecureSession/client.ts
- src/tests/functions/createThreeDSecureSession.test.ts
To reflect changes on our preview API
> Removes cardholder present from response

- examples/card-with-3ds/index.html
- package.json
- scripts/build-and-publish.sh
- src/functions/createThreeDSecureSession/createThreeDSecureSession.ts
Detect test mode and use the test mode app ID when appropriate.
> fix: correct test mode app id

- package.json
- src/functions/createThreeDSecureSession/client.ts
- src/functions/createThreeDSecureSession/createThreeDSecureSession.ts
https://duffel.slack.com/archives/C086HG45GLF/p1736412996355429
> Allow cardholder present to be null

- config/esbuild.base.config.js
- package.json
- src/functions.ts
- src/functions/createThreeDSecureSession/createThreeDSecureSession.ts
- src/functions/hasService.ts
__what__
Adds new functions to help merchants determine if services are present on an offer or seat map.
> Exposes `hasService` helper

- package.json
- src/index.ts
__what__
To be able to consume the functions from a node import we need to export them from this index file.
> Adds export

- package.json
- src/components/Stays/lib/getRateLabel.ts
- src/stories/StaysRoomRateCard.stories.tsx
by updating the label function
> Introduce stays deposit rate cards

- package.json
- yarn.lock
To release changes from https://github.com/duffelhq/duffel-api-javascript/releases/tag/v4.12.3
> bump types package

- package.json
- src/components/DuffelCardForm/DuffelCardForm.tsx
__what__
Adds a loading state to the card form component to make the experience better when loading it -- prevents UI jump, prevents blank screen when moving to payment form. 
https://github.com/user-attachments/assets/2c5d737f-59b0-4f9a-8131-765bec0fd314
> Adds card form loading state

- package.json
- yarn.lock
To resolve this critical vulnerability: https://github.com/duffelhq/duffel-components/security/dependabot/86
> chore: bumps form data to fix critical vulnerability
