package.json
__what__
By default, semantic-releases expects releases to happen on the `master` branch. Since we didn't have a config on package json to specify otherwise, the release workflow failed. This PR fixes that.
=> Adds missing branches config

package.json, src/components/DuffelAncillaries.tsx, src/examples/full-stack/index.html, src/lib/captureErrorInSentry.ts, src/tests/components/DuffelAncillaries.test.tsx, yarn.lock
__what__
We had a couple of issues pop up in Sentry today: 
- Cannot read properties of undefined (reading 'map') on `formatSeatMaps`
- Cannot read properties of undefined (reading 'expires_at') on `offerIsExpired`
After investigating and testing, I still couldn't get to the bottom of the issue. The only piece of visibility we currently have is the `offer_id`. In order to make sure we can properly support folks integrating with the ancillaries component, this PR proposes capturing some relevant and non-sensitive data that would help us pin down issues, fixes bugs, create helpful error messages and document common integration issues and their resolution.
=> Sentry improvements

package.json
__what__
with the latest push to main, the ["Release" workflow](https://github.com/duffelhq/duffel-components/actions/runs/5219530365/jobs/9421469596) ran successfully but semantic-release evaluated that "There are no relevant changes, so no new version is released." 
This update includes a breaking change comment and returns package json to the current release version on npm to force (and verify) that semantic release will create a major bump to v3.0.0
=> Sets package version to current one to force new push

.github/workflows/release.yml
__what__
This adds missing env variables to the release step. They will be used to build the component.
=> Fixes broken release step on CI

.eslintrc.js, config/esbuild.cdn.config.js, config/esbuild.dev.config.js, config/esbuild.react.config.js, scripts/generate-fixture.ts, src/components/DuffelAncillaries.tsx, src/components/ErrorBoundary.tsx, src/components/Icon.tsx, src/examples/full-stack/server.mjs, src/examples/just-typescript/src/index.ts, src/examples/react-app/src/index.tsx, src/lib/captureErrorInSentry.ts, src/lib/fetchFromDuffelAPI.ts, src/lib/formatDate.ts, src/lib/getBaggageServiceDescription.ts, src/lib/getTotalAmountForServices.ts, src/lib/logging.ts, src/lib/retrieveOffer.ts, src/lib/retrieveSeatMaps.ts, src/tests/lib/logging.test.tsx
__what__
We have gotten a couple of Sentries that were hard to gather information about. It takes too much time to go into GCP to check logs and even in that case it, the entries from platform might not be informative to help us debug the issue. With this change we introduce Sentry breadcrumbs to our logs to give use more visibility into what the component tried to do prior to failing:
=> Log update

src/styles/components/SeatInfo.css
We were missing a bit of spacing between selected seat components.
View on Jira:
Before:
After:
=> Increase spacing below selected seat

.storybook/__snapshots__/Storyshots.test.js.snap, src/components/DuffelAncillaries/bags/BaggageSelectionModalFooter.tsx, src/components/DuffelAncillaries/bags/BaggageSelectionModalHeader.tsx, src/components/DuffelAncillaries/seats/SeatSelectionModalFooter.tsx, src/components/DuffelAncillaries/seats/SeatSelectionModalHeader.tsx, src/stories/DuffelAncillaries.stories.tsx
There's no need to have the indicator dots and disabled buttons when we only have a one way flight (and one passenger for seats).
Check out the "One way one passenger story" for an interactive test.
Before:
After:
=> [UXP-3053] fix: cleaner interface when only one way flight

src/components/DuffelAncillaries/seats/SeatMap.tsx
Display seatmaps as unavailable if no cabins are present, rather than erroring in the code later.
https://duffel.atlassian.net/browse/FR-4421
=> fix: display proper warning message if no cabins present

.storybook/__snapshots__/Storyshots.test.js.snap, src/components/DuffelAncillaries/DuffelAncillaries.tsx, src/components/DuffelPayments/DuffelPayments.tsx, src/lib/hasHighLuminance.ts, src/stories/Button.stories.tsx, src/styles/components/Button.css
This adds a secondary colour and outline for buttons if the accent color is too bright using the luminance function as in Links.
White accent color story:
src="https://github.com/duffelhq/duffel-components/assets/1416759/88690843-6564-4213-9479-768c5c017ce3">
Regular accent color:
=> fix: handle white accent color

.tool-versions
__what__
Following [Norberto's lead](https://github.com/duffelhq/design-system/pull/465) and replicating this here:
> asdf no longer supports non-reproducible versions and they state that in the past that was by mistake not design. We shouldn't either.
=> fix: use specific version for node

package.json
As on October 24 2023 Node.js 20.x was transitioned into Long Term Support (LTS), any project that will update to this version won't be able to use this package.
I believe that everything should work fine with Node.js 20.x too.
=> Allow to use any nodejs version starting from 18

src/tests/lib/convertDurationToString.test.tsx, src/tests/lib/getDurationString.test.tsx
As per this thread: https://duffel.slack.com/archives/C013XQ3T2J1/p1700039584322359?thread_ts=1700004885.432129&cid=C013XQ3T2J1
We copied in these functions recently from the dashboard code, it makes sense to copy over the tests too.
=> test: add tests for recently added date functions from the dashboard

package.json, src/components/DuffelAncillaries/Card.tsx
__what__
Small fixes to get the ancillaries card to be of `type` `button` to prevent form submissions.
=> type=button on ancillaries card

package.json, scripts/build-and-publish.sh, src/types/index.ts, yarn.lock
__what__
We can't export just types from `src/types/index.ts` file otherwise esbuild will fail build. That happens because `@duffel/api/types` is not an actual module, just a typescript declaration. This small change allows the export from @duffel/api to be added afterwards.
=> Improves build script

src/lib/formatAvailableServices.ts
__What__
We have an [issue](https://github.com/duffelhq/duffel-components/issues/184) where the API is returning `null` on for an `offer`'s `available_services`. This should not be the case and needs to be corrected. But to avoid the component crashing in the meantime, we'll add a small guard.
=> Update formatAvailableServices to support null available_services

src/examples/next/src/app/DuffelComponents.tsx
**Screenshots** of the issue:
**Changes Made:**
- Corrected import statements in DuffelComponent to accurately reference @duffel/components
- With this fix, the imports now point to the correct module, ensuring functions as expected.
=> Fix import issue in DuffelComponents

.eslintrc.js, src/components/DuffelCardForm/DuffelCardForm.tsx, src/components/DuffelCardForm/Example.tsx, src/components/DuffelCardForm/lib/getIFrameEventListener.ts, src/components/DuffelCardForm/lib/getIFrameOriginForEnvironment.ts, src/components/DuffelCardForm/lib/getIframeURL.ts, src/components/DuffelCardForm/lib/getPathnameForIntent.ts, src/components/DuffelCardForm/lib/postMessageToCreateCardForTemporaryUse.ts, src/components/DuffelCardForm/lib/postMessageToSaveCard.ts, src/components/DuffelCardForm/lib/postMessageToStoreCardForTemporaryUse.ts, src/components/DuffelCardForm/lib/postMessageWithStyles.ts, src/components/DuffelCardForm/lib/types.ts, src/components/DuffelCardForm/lib/useDuffelCardFormActions.ts, src/stories/DuffelCardForm.stories.tsx
__What__
We want to support the ability for merchants to save cards as well as use saved cards. This updates the interface to allow them to do so. More documentation on how this works with the token proxy is coming soon.
=> Adds interface for save card

package.json, src/lib/hasServiceOfSameMetadataTypeAlreadyBeenSelected.ts, src/tests/lib/hasServiceOfSameMetadataTypeAlreadyBeenSelected.test.ts, src/types/DuffelAncillariesProps.ts
This PR contains a different way of addressing the baggage restriction bug reported in https://duffel.atlassian.net/browse/UXP-3321. I think we aren't taking into account that services can apply to [multiple segments ](https://duffel.com/docs/api/v1/offers/schema#offers-schema-available-services-available-services-segment-ids) correctly but please let me know if I misunderstood something. Added a test and a video of the new behaviour here:
https://github.com/duffelhq/duffel-components/assets/1416759/714e3ece-1eda-438e-87ab-f92d9cd9a6cb
=> UXP-3321 Another attempt at a fix for the baggage restriction bug

src/components/DuffelNGSView/DuffelNGSView.tsx, src/components/DuffelNGSView/lib/index.ts, src/stories/DuffelNGSView.stories.tsx, src/styles/components/DuffelNGSView.css, src/styles/global.css
This sets the foundation for the table view for desktop.
Currently using some fake tabular data while I'm waiting for some answers on the data structure. We could merge this as is to allow us to branch of and develop in parallel, or wait for that and sort out the offers structure in here before merging.
I've included column highlighting, but no sorting just yet. I've also left the first column as a TODO as the new components (carrier title, flight summary, whatever goes into "View details") will slot in there.
=> Foundation for desktop table view

src/components/DuffelNGSView/DuffelNGSView.tsx, src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/fixtures/offers/off_0000Adw9MD7yDHXIXxdjfG.json, src/lib/colors.ts, src/stories/DuffelNGSView.stories.tsx, src/styles/colors.css, src/styles/components/DuffelNGSView.css
Adds slice fare card components to the table view to allow more detailed offer comparison:
=> [UXP-3349] Detailed offer comparison for NGS

package.json, src/components/Stays/StaysRoomRateCard.tsx, src/fixtures/accommodation/acc_0000AWr2VsUNIF1Vl91xg0.json, yarn.lock
We now return an array of available payment methods in the API. We should display all of the options to the customer on the rate card.
We will not actually return multiple payment methods for a rate at this point, so this is mainly futureproofing for later development. 
Also bumps the version of the JS API so we get the correct values from the API.
=> [STAYS-1271] use available payment methods in stays rate card

src/components/Stays/StaysRoomRateCard.tsx, src/fixtures/accommodation/acc_0000AWr2VsUNIF1Vl91xg0.json, src/stories/StaysRoomRateCard.stories.tsx, src/styles/components/StaysRoomRateCard.css
Rates that are non refundable now have a non-refundable indicator
I also threw in some changes to the story book that allows us to see cards side by side. This is because we may have reached the limit at which we can display rate differentiators in these cards, and a redesign will soon be warranted.
To see what this situation looks like, see two different rate cards below. One with fewer properties than the other.
To fix this, the contained components' differentiators are now separated by "justify-content: space-between" instead of a fixed 40px margin to allow us to scale with different types of rate cards side by side.
It is important to take note that the parent must have a fixed height in order to accommodate the entirety of the content properly. Maybe we want to move the fixed height …
=> Non refundable rate indicator

src/components/DuffelAncillaries/seats/SeatSelectionCard.tsx, src/lib/hasAvailableSeatService.ts, src/stories/DuffelAncillaries.stories.tsx, src/styles/components/Card.css, src/tests/lib/hasAvailableSeatService.test.tsx
__what__
This PR corrects the disable state of the seat map card.  
1. It should not show the hover state when the button is disabled. [Reported issue here](https://github.com/duffelhq/duffel-components/issues/214)
2. It should disable the card if there's no available services, even when the seat map is returned. [Reported issue here](https://github.com/duffelhq/duffel-components/issues/213)
=> Seat map fixes

src/components/DuffelNGSView/DuffelNGSView.tsx, src/components/DuffelNGSView/NGSTable.tsx, src/components/DuffelNGSView/lib/group-offers-for-ngs-view.ts, src/components/DuffelNGSView/lib/index.ts, src/components/DuffelNGSView/lib/sort-ngs-rows.ts, src/stories/DuffelNGSView.stories.tsx, src/stories/NGSSliceFareCard.stories.tsx, src/styles/components/NGSTable.css
This has most of the feedback from the demo work in it:
- fix for the styles missing (I forgot the wrapper)
- remove prev & next shelves to avoid confusion
- simplify NGSShelf type to match the API
- make sure we show multiple fare brands for the same shelf if they exist
There are two small bits still missing that could either fit in here or go in a separate PR later:
- _icon - discussion [here](https://duffel.slack.com/archives/C06A8HUCDPW/p1708974003649439)_ - we decided not to change this in the end
- will update NGS shelf description once I have it from Dan
=> NGS Demo Feedback

src/components/DuffelNGSView/lib/index.ts
Updates the descriptions of the `plus`, `premium` and `lux` shelves in the NGS view so that they no longer reference economy or advance seat selection / other perks. This is due to how the weird NGS calculation works and while we expect these high value seats to have these perks, we can't guarantee it.
=> update descriptions for plus, premium and lux shelves

package.json, src/components/MapboxPlacesLookup/MapboxPlacesLookup.tsx
__what__
Popover styles were not showing up when integrated outside of storybook. This adds the missing styles wrapper.
=> Adds missing style wrapper

.yarn/sdks/prettier/package.json, config/esbuild.base.config.js, examples/card-form-no-react/index.html, examples/card-form-no-react/server.mjs, src/components/DuffelCardForm/DuffelCardFormCustomElement.tsx, src/components/DuffelCardForm/lib/types.ts, src/custom-elements.ts
__what__
This PR exposes the card form as a custom element and a test page for it. 
To run the test page locally use: 
```sh
yarn dev
```
and 
```sh
DUFFEL_API_URL=https://api.duffel.com DUFFEL_API_TOKEN=<token> node examples/card-form-no-react/server.mjs
```
=> Card form custom element

examples/card-form-no-react/index.html, package.json, src/components/MapboxPlacesLookup/MapboxPlacesLookupCustomElement.tsx, src/styles/components/PlacesLookup.css
To prevent styles bleeding (to button in particular).
Includes version bump so I can use it in https://github.com/duffelhq/platform/pull/17902
https://github.com/duffelhq/duffel-components/assets/1416759/51967ead-d75d-48f3-84e9-c4a89932a33a
=> Add shadow root to Mapbox places look up

package.json, src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/components/DuffelNGSView/NGSTable.tsx, src/components/DuffelNGSView/lib/deduplicate-mapped-offers-by-fare-brand.ts, src/components/DuffelNGSView/lib/group-offers-for-ngs-view.ts, src/fixtures/offer-requests/orq_0000Ab7taNqbK8y5YqW6Zk.json, src/stories/DuffelNGSView.stories.tsx, src/styles/components/DuffelNGSView.css, src/styles/components/NGSTable.css, src/tests/lib/groupOffersForNGSView.test.tsx
This includes the following fixes:
- some CSS changes for overflow since the shelf info display was getting cut off, and the scrolling still didn't work perfectly
- we now deduplicate the offers within a fare brand according to the logic described here: https://www.notion.so/duffel/NGS-Technical-Scoping-26df8e8fb8db40e19bd661b748810622?pvs=4#3190288ac96f474ea603beed2777c5a0. I've also added both a test and story for the case provided
Demos of the fixes:
Shelf info display:
https://github.com/duffelhq/duffel-components/assets/1416759/8adbd1ec-2ee1-485f-bb02-703662c8d3a3
Scrolling:
https://github.com/duffelhq/duffel-components/assets/1416759/a3fa1577-1de6-42ec-bccb-8edcc5b5c73b
Deduplicated offers from the example in Notion:
https://github.com/duffelhq/duffel-components/assets/1416759/0b3671 …
=> NGS fixes after demo feedback

package.json, src/components/MapboxPlacesLookup/MapboxPlacesLookup.tsx, src/components/MapboxPlacesLookup/MapboxPlacesLookupCustomElement.tsx, src/styles/global.css
__what__
We want to enable an initial input value on the component. This PR exposes that prop. 
Also, this is a very atomic component which's styles must align with what the integrator wants. So, this PR removes all styling from the component, removes the shadow root to enable to enable customisation through 2 classes: one for the input and one for the popup.
=> Mapbox component updates

package.json, src/components/DuffelNGSView/DuffelNGSView.tsx, src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/components/DuffelNGSView/NGSTable.tsx, src/components/DuffelNGSView/lib/deduplicate-mapped-offers-by-fare-brand.ts, src/components/DuffelNGSView/lib/group-offers-for-ngs-view.ts, src/components/DuffelNGSView/lib/sort-ngs-rows.ts, src/stories/DuffelNGSView.stories.tsx, src/stories/OfferSlice.stories.tsx, src/stories/OfferSliceModal.stories.tsx, src/stories/SliceSummary.stories.tsx, yarn.lock
I've got a few NGS fixes to work through today, they'll probably come split in a few PRs and at the end I'll do a release.
For this one, James pointed out that we should be showing the origin & destinations in the breadcrumbs from the offer request, rather than the first offer, since they might have searched for a city rather than airport: https://duffel.slack.com/archives/C06A8HUCDPW/p1711114502922789
This required a slight refactor as the component just took in the list of offers directly before. It now accepts an offer request, and then passes down the list of offers from there. Changing the types touched a lot of files (they're not just "Offer[]" because "available_services" need to be omitted). 
This could be considered a breaking change. As far as I know the only usage of this …
=> Change NGS to accept offer request rather than list of offers

src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/components/DuffelNGSView/lib/deduplicate-mapped-offers-by-fare-brand.ts, src/components/DuffelNGSView/lib/get-max-baggages-for-offer-slice.ts, src/stories/DuffelNGSView.stories.tsx, src/stories/NGSSliceFareCard.stories.tsx, src/styles/components/NGSSliceFareCard.css, src/styles/components/NGSTable.css
This contains a couple slice fare card fixes:
- with long fare brand names, the display would get misaligned (see below)
- we would sometimes show checked baggage as available even though quantity was 0, for example here: https://duffel.slack.com/archives/C06A8HUCDPW/p1711114347885839 (this was because we were missing a filter on the first step)
- includes more thorough stories for the slice fare card
Misaligned display before:
More even alignment when fare brand names have different lengths now (from stories):
=> Slice fare card fixes

src/components/DuffelNGSView/lib/sort-ngs-rows.ts, src/stories/DuffelNGSView.stories.tsx
I thought I had handled this case but I hadn't, so sorting didn't apply properly when there were empty values in a column (which is very often). It should work better now, and I've expanded the story to demonstrate:
https://github.com/duffelhq/duffel-components/assets/1416759/3bda041b-ab5b-4da4-8bd6-920977878aff
=> Fix sorting when empty values are present

src/components/DuffelNGSView/NGSTable.tsx
On the dashboard we're seeing weird behaviour where the "View details" modal for NGS slices is buggy - it is laggy to click and close, the screen goes black, etc.
I don't see any of that in stories. My current speculative theory is that this could be happening because the tables on the dashboard are much larger than in the examples (hundreds vs a couple), and we were creating one modal per row. This refactors so we only create one modal per table. 
Even if this doesn't fix the problem I still think it's a nice refactor. I would test it locally but it's quite hard with setting up a local dashboard with all the NGS feature flags to then use the local instance of duffel components. So once I've published a (canary) release I'll test that on dashboard staging.
=> Slice modal fix (hopefully)

.prettierignore, package.json, src/components/DuffelNGSView/NGSTable.tsx, src/fixtures/offer-requests/orq_duplicates.ts, src/stories/DuffelNGSView.stories.tsx, src/tests/lib/groupOffersForNGSView.test.tsx
This adds:
- a large realistic fixture (taken from a real dashboard search)
- extract the duplicated offers into a "fixture" (I know it doesn't match the format exactly but that seemed like it was the best fit, and is used in both unit tests and stories, which have issues importing/exporting from each other)
- the large fixture showed me there was a little bug with expanding + sorting - we had accidentally been referring to the unsorted rows array in a couple places
- bump version so we can get the new fixes in the dashboard
=> Release components with NGS fixes

src/components/OfferSlice/OfferSlice.tsx, src/fixtures/offers/off_0000AguUNlT6zsvmL0UBKn.json, src/stories/OfferSliceModal.stories.tsx
The layover durations appeared as negative: https://duffel.slack.com/archives/C06A8HUCDPW/p1712945487283059
I believe because the "start" and "end" dates were switched. 
I added a test offer and story for that case. 
After:
=> Fix negative layovers bug

src/components/OfferSliceModal/OfferSliceModal.tsx
This PR takes the offer slice modal header out of the ModalBody as that is scrollable.
Before:
https://github.com/duffelhq/duffel-components/assets/1416759/3e1cfcbb-a152-441b-a8bb-e2cc2c5c15f0
After:
https://github.com/duffelhq/duffel-components/assets/1416759/873cb5d4-61d6-4805-8cda-278eb8aef555
=> Make offer slice modal header stick to top

package.json, src/styles/components/SliceSummary.css
__what__
Ensures slice width stays consistent when placed in NGS container. 
| Before | After |
|---|---|
| <img width="737" alt="Screenshot 2024-04-15 at 1 44 15 PM" src="https://github.com/duffelhq/duffel-components/assets/2934495/73786786-e25b-440f-87dd-267e9d743c14"> |  <img width="680" alt="Screenshot 2024-04-15 at 1 45 05 PM" src="https://github.com/duffelhq/duffel-components/assets/2934495/b6a28465-022b-4275-8b54-4e1031e03e2a"> |
[Reported here](https://duffel.slack.com/archives/C06A8HUCDPW/p1712838111163279).
=> Fixes variable slice width

src/components/DuffelNGSView/NGSTable.tsx, src/styles/components/NGSTable.css
Add fare brand name and trip type: 
As per https://duffel.slack.com/archives/C06A8HUCDPW/p1713179082461439?thread_ts=1713178517.871889&cid=C06A8HUCDPW
=> Add fare brand name and trip type

package.json, src/components/DuffelNGSView/DuffelNGSView.tsx, src/components/DuffelNGSView/NGSTable.tsx, src/styles/components/DuffelNGSView.css, src/styles/components/NGSTable.css
This is the first part of https://duffel.atlassian.net/browse/UXP-3437?atlOrigin=eyJpIjoiNmMyYTMyZjMwNTY1NDBjZjk1ZTY0MWVkYWZkMzk4NjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ.
It will require more than just a bump on the dashboard, started working on that here: https://github.com/duffelhq/dashboard/pull/4919
Some notes:
Currently the NGS table is structured as an html table. These have some funny [limitations](https://css-tricks.com/position-sticky-and-table-headers/) with sticky positioning, e.g. you have to put it on `th` elements rather than `thead` or `tr`.
More importantly, having any parent with overflow  set can break stickiness. In this case we have a few on the dashboard - on the page, its content, and around the NGS table (we had scrolling issues before). I’ve tried unsetting them but …
=> Make NGS table header sticky

package.json, src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/styles/components/NGSTable.css, src/styles/utilities.css
__what__
If you are browsing flights it's easier as a customer to be able to see what are the cabin classes of segments by hovering over the "multiple cabins tag". so you don't need to leave the NGS view. This PR implements that:
https://github.com/duffelhq/duffel-components/assets/2934495/13d84ab4-f92c-43eb-8a70-aa93f117434d
- [Reported on slack ](https://duffel.slack.com/archives/C06A8HUCDPW/p1715092788231169?thread_ts=1714557642.240609&cid=C06A8HUCDPW)
=> Adds mixed cabin help popover

package.json
💁 A different (perhaps old?) repository name was used as part of https://github.com/duffelhq/duffel-components/pull/166. While that URL correctly redirects to this repository, it could be confusing for future readers.
```
$ curl -I https://github.com/duffelhq/duffel-checkout
HTTP/2 301
server: GitHub.com
date: Mon, 20 May 2024 12:29:59 GMT
content-type: text/html; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
location: https://github.com/duffelhq/duffel-components
...
```
This change updates the URL for this repository accordingly.
=> Update source URL in package manifest

package.json, src/components/DuffelCardForm/DuffelCardForm.tsx, src/components/DuffelCardForm/DuffelCardFormCustomElement.tsx, src/components/DuffelCardForm/lib/getIFrameEventListener.ts, src/components/DuffelCardForm/lib/types.ts, src/custom-elements.ts
For PCI compliance, we need to be able to detect CSP violations wherever we use the card form ([Dashboard](https://duffel.atlassian.net/browse/UXP-3447) and [Links](https://duffel.atlassian.net/browse/UXP-3448)). The initial [plan](https://duffel.slack.com/archives/C013XQ3T2J1/p1714485079430949?thread_ts=1713781035.301879&cid=C013XQ3T2J1) was to do that there using the `securitypolicyviolation event`. I tried to do that but couldn't detect the event on dashboard. I believe it's because the event happens within the iframe and isn't bubbled up to the parent window (similar [StackOverflow](https://stackoverflow.com/questions/44949085/is-there-any-event-fired-when-x-frame-options-content-security-policy-are-viol)). I was able to detect it inside the iframe, so I've added a function …
=> Add handler for security policy violations for DuffelCardForm

package.json, src/components/DuffelNGSView/lib/deduplicate-mapped-offers-by-fare-brand.ts, src/stories/NGSSliceFareCard.stories.tsx
Make sure that all fare brand names are title cased and don't have any underscores (e.g. `premium_economy`).
To address comments from https://www.notion.so/NGS-for-Delta-6a67026c68864c3988afe42cbaa04b3b?d=5936b24da11740898c7f328f34479fcc&pvs=4#62db6d750cea4a499a63e224a8dd720a and https://www.notion.so/NGS-for-Delta-6a67026c68864c3988afe42cbaa04b3b?d=74c18a2b5b334eec8fb742801ddcd2f9&pvs=4#3b535cf084554bf59af1dda451047971.
New story screenshot:
=> Consistent casing for fare brand names in NGS

package.json, src/components/DuffelNGSView/lib/deduplicate-mapped-offers-by-fare-brand.ts
It seems that using lodash in [this recent PR ](https://github.com/duffelhq/duffel-components/pull/291) breaks the exports for at least some stays components (as seen on [Chromatic builds ](https://www.chromatic.com/build?appId=5f5f5a24adceb80022a613f8&number=16953) when I tried to bump the version in dashboard). I've tried publishing a canary version with lodash and one without (using the `replace` seen here), and the latter works fine: https://github.com/duffelhq/dashboard/pull/4963
=> Replace lodash with regex for start case in NGS fare brand name

package.json, src/components/Stays/StaysRoomRateCard.tsx, src/components/Stays/lib/getRateLabel.ts, src/stories/StaysRoomRateCard.stories.tsx, src/tests/lib/getRateLabel.spec.ts
This makes us better able to convey that a rate is payable by card IMMEDIATELY
We then illustrate that this is possible via storybook (See third rate with multiple payment methods for pay_now type)
=> Make pay now rates by card possible

package.json, src/components/shared/SliceCarriersTitle.tsx
As reported in this thread, our "operated by" text was incorrect. I think the condition should not have been negated.
Now (for the [offer](https://jet.x15.xyz/air/offers/off_0000AiihR5LtcpCV0NGu65/view_api_offer) in the Slack thread):
=> Fix segments carrier title condition

package.json
I didn't realise 3.7.15 had already been published 5 days ago: https://www.npmjs.com/package/@duffel/components?activeTab=versions
=> Verion bump

package.json, src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/components/shared/SliceCarriersTitle.tsx, src/fixtures/offer-requests/orq_0000Ab7taNqbK8y5YqW6Zk.json, src/stories/NGSSliceFareCard.stories.tsx, src/styles/components/NGSSliceFareCard.css, src/styles/components/SliceCarriersTitle.css
A couple more things have been requested for NGS:
https://duffel.atlassian.net/browse/UXP-3498 - when the attribute is null, don't display it. Example:
[Context on Slack](https://duffel.slack.com/archives/C06A8HUCDPW/p1718308935457959)
Making the flight numbers more visible ([context on Slack](https://duffel.slack.com/archives/C06A8HUCDPW/p1718355504097939)):
Doesn't look amazing with a long title but we just want to get something done quickly:
=> [UXP-3498] Not showing null atrributes for NGS

package.json, src/functions/createThreeDSecureSession/createThreeDSecureSession.ts
__what__
This PR will make 2 changes to comply to our 3DS API. 
1. Updates the app ID to match that used in production 
2. Updates the `external_id` to be the new `challenge_component_id ` attribute instead
=> Patches 3DS function

.storybook/main.ts, src/stories/AirlineLogo.stories.tsx, src/stories/Button.stories.tsx, src/stories/Icon.stories.tsx, src/stories/MapboxPlacesLookup.stories.tsx, src/stories/NGSSliceFareCard.stories.tsx, src/stories/OfferSlice.stories.tsx, src/stories/OfferSliceModal.stories.tsx, src/stories/PlacesLookup.stories.tsx, src/stories/SliceSummary.stories.tsx
This allows our newer storybook samples to run without having to import React in the file heading
This also removes the need to import react from older examples
NGS Airline Selector does not seem to want to let go of the import even after the update. So I kept it there. Pretty bizaare!
This is not the case for all the other components
The revisions applied are taken mostly from the storybook documentation here:
https://storybook.js.org/docs/configure/integration/compilers#the-swc-compiler-doesnt-work-with-react
=> Configure SWC compiler to import react runtime by default

package.json, src/styles/components/SeatMap.css
To include bottom padding, making sure the last row of the seat map is visible.
| Before | After |
|---|---|
[Reported on slack](https://duffel.slack.com/archives/C013XQ3T2J1/p1730740197878659)
=> Updates seatmap

README.md, package.json
- Replaces Duffel Payments link with one to the card form implementation guide
=> Update links to card implementation guides

package.json, src/functions/createThreeDSecureSession/client.ts, src/functions/createThreeDSecureSession/createThreeDSecureSession.ts, src/tests/functions/createThreeDSecureSession.test.ts
Our 3DS Session API supports an `exception` field to specify the exception used to opt out of authenticating the payment with the card issuer. This PR adds support for that field when the session is initialised by the Card Component.
=> Add support for 3DS Session exception

src/components/DuffelAncillaries/DuffelAncillaries.tsx, src/stories/DuffelAncillaries.stories.tsx, src/types/DuffelAncillariesProps.ts
It'd make the integration for some customers easier if they can pass in previous state to the component with the way their checkout flow works.
Same change will be done on react native components once we're happy with the interface.
Try it on the new story:
=> Allow passing selection into ancillaries component

package.json, src/components/DuffelAncillaries/seats/Element.tsx, src/components/DuffelAncillaries/seats/SeatElement.tsx, src/components/DuffelNGSView/NGSShelfInfoCard.tsx, src/components/DuffelNGSView/NGSSliceFareCard.tsx, src/components/DuffelNGSView/NGSTable.tsx, src/components/DuffelNGSView/lib/group-offers-for-ngs-view.ts, src/components/DuffelNGSView/lib/index.ts, src/components/Stays/lib/getRateLabel.ts, src/fixtures/seat-maps/seat_map_with_restricted_seat_general.json, src/lib/getSliceDetails.ts, src/lib/isAmenityElement.ts, src/lib/isSeatElement.ts, src/stories/OfferSlice.stories.tsx, src/stories/OfferSliceModal.stories.tsx, src/stories/SeatMap.stories.tsx, src/stories/SliceSummary.stories.tsx, yarn.lock
Prompted by a [customer complaint](https://duffel.atlassian.net/browse/FR-8249?focusedCommentId=43085). 
It will look like this once it's published:
=> [FR-8249] Adds support for seat map element of type `restricted_seat_general`

src/functions/createThreeDSecureSession/client.ts
User agent for 3DS was the same as the ancillaries component one, this was a mistake.
=> [TSP-206] Fixes user agent

package.json, src/components/DuffelNGSView/lib/deduplicate-mapped-offers-by-fare-brand.ts, src/components/DuffelNGSView/lib/group-offers-for-ngs-view.ts, src/fixtures/offer-requests/spirit.json, src/stories/DuffelNGSView.stories.tsx
Turns out it was mainly the fare brand deduplication only looking at the first slice
=> Spirit fix
